// Generated by CoffeeScript 1.6.3
(function() {
  var me;

  this.time = null;

  me = this;

  this.initEditor = function(el, duration, breaks) {
    var b, _i, _len;
    if (duration == null) {
      duration = 0;
    }
    if (breaks == null) {
      breaks = [];
    }
    me.time = new Timeline(el, duration);
    for (_i = 0, _len = breaks.length; _i < _len; _i++) {
      b = breaks[_i];
      me.time.addSegment(b);
    }
    return me.time;
  };

  $(document).ready(function() {
    $('#init').click(function(e) {
      initEditor($('#c'), 3600);
      e.preventDefault();
      return true;
    });
    return $('#addSegment').submit(function(e) {
      var w, x;
      e.preventDefault();
      x = $('#x-input').val();
      w = $('#w-input').val();
      if (x === '' || w === '') {
        alert('please enter an x and width value');
        return;
      }
      return me.time.addSegment(x, w);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
