// Generated by CoffeeScript 1.6.3
(function() {
  this.Timeline = (function() {
    Timeline.prototype.container = null;

    Timeline.prototype.d3Element = null;

    Timeline.prototype.svg = null;

    Timeline.prototype.x = null;

    Timeline.prototype.xAxis = null;

    Timeline.prototype.duration = 0;

    Timeline.prototype.segments = [];

    Timeline.prototype.margin = {
      top: 10,
      right: 10,
      bottom: 10,
      left: 10
    };

    function Timeline(container, seconds) {
      this.container = container;
      if (seconds == null) {
        seconds = 0;
      }
      if (typeof this.container === 'string') {
        this.container = $(this.container).find(':first');
      }
      if (this.container.attr('id') === '' || this.container.attr('id') === 'undefined') {
        this.container.attr('id', 't-' + this.randID());
      }
      this.d3Element = d3.select('#' + this.container.attr('id'));
      this.x = d3.time.scale().domain([new Date('2014-01-01 00:00:00'), d3.time.second.offset(new Date('2014-01-01 00:00:00'), seconds)]).rangeRound([0, this.container.width() - this.margin.left - this.margin.right]);
      this.xAxis = d3.svg.axis().scale(this.x).orient('bottom').ticks(d3.time.seconds, 100000).tickFormat(d3.time.format('%H:%M:%S.%L'));
      if (seconds > 0) {
        this.setDuration(seconds);
      }
      this.svg = this.d3Element.append('svg');
      this.svg.attr('width', this.container.width()).attr('height', this.container.height());
      this.svg.append('g').attr('transform', "translate(" + this.margin.left + "," + this.margin.top + ")");
      this.svg.append('g').attr('class', 'x axis').attr('transform', "translate(0, " + (this.container.height() - this.margin.top - this.margin.bottom) + ")").call(this.xAxis);
    }

    Timeline.prototype.addSegment = function(segment) {
      this.segments.push(segment);
    };

    Timeline.prototype.setDuration = function(seconds) {
      this.duration = 1000;
      return this.x.range([0, this.duration]);
    };

    Timeline.prototype.randID = function() {
      var i, possible, text, _i;
      text = "";
      possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
      for (i = _i = 0; _i <= 20; i = ++_i) {
        text += possible.charAt(Math.floor(Math.random() * possible.length));
      }
      return text;
    };

    return Timeline;

  })();

}).call(this);

/*
//@ sourceMappingURL=Timeline.map
*/
