// Generated by CoffeeScript 1.6.3
(function() {
  this.initCanvas = function() {
    var canvas_height, canvas_width, i, rect, rect_layer, stage, t, text_layer, _i;
    canvas_width = 600;
    canvas_height = 100;
    stage = new Kinetic.Stage({
      container: 'c',
      width: canvas_width,
      height: canvas_height
    });
    text_layer = new Kinetic.Layer({
      id: 'text-layer'
    });
    for (i = _i = 0; _i <= canvas_width; i = _i += 100) {
      t = new Kinetic.Text({
        text: i,
        align: 'right',
        fill: 'black',
        x: 0,
        y: i
      });
      text_layer.add(t);
    }
    rect_layer = new Kinetic.Layer({
      id: 'rect-layer'
    });
    rect = new Kinetic.Rect({
      x: 20,
      y: 20,
      width: 50,
      height: 30,
      fill: 'green',
      stroke: 'black',
      strokeWidth: 2,
      opacity: 0.4,
      draggable: true,
      dragBoundFunc: function(pos) {
        return {
          x: pos.x,
          y: this.getAbsolutePosition().y
        };
      }
    });
    rect.on('mouseover', function() {
      this.setOpacity(1);
      document.body.style.cursor = 'pointer';
      return rect_layer.draw();
    });
    rect.on('mouseout', function() {
      this.setOpacity(0.4);
      document.body.style.cursor = 'default';
      return rect_layer.draw();
    });
    rect_layer.add(rect);
    stage.add(text_layer);
    stage.add(rect_layer);
    return stage;
  };

}).call(this);
