// Generated by CoffeeScript 1.6.3
(function() {
  this.initCanvas = function(opts) {
    var stage;
    if (opts == null) {
      opts = {};
    }
    return stage = new TimelineStage(opts);
  };

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
