// Generated by CoffeeScript 1.6.3
(function() {
  this.initCanvas = function() {
    var layer, rect, stage;
    stage = new Kinetic.Stage({
      container: 'c',
      width: 600,
      height: 100
    });
    layer = new Kinetic.Layer();
    rect = new Kinetic.Rect({
      x: 20,
      y: 20,
      width: 50,
      height: 30,
      fill: 'green',
      stroke: 'black',
      strokeWidth: 2,
      opacity: 0.4,
      draggable: true,
      dragBoundFunc: function(pos) {
        return {
          x: pos.x,
          y: this.getAbsolutePosition().y
        };
      }
    });
    rect.on('mouseover', function() {
      this.setOpacity(1);
      document.body.style.cursor = 'pointer';
      return layer.draw();
    });
    rect.on('mouseout', function() {
      this.setOpacity(0.4);
      document.body.style.cursor = 'default';
      return layer.draw();
    });
    layer.add(rect);
    return stage.add(layer);
  };

}).call(this);
