// Generated by CoffeeScript 1.6.3
(function() {
  this.TimelineSegment = (function() {
    TimelineSegment.prototype.opts = {
      x: 0,
      duration: 1000,
      rectOpacity: 0.4,
      rectHoverOpacity: 0.8
    };

    TimelineSegment.prototype.layer = null;

    TimelineSegment.prototype.group = null;

    TimelineSegment.prototype.shape = null;

    TimelineSegment.prototype.delete_btn = null;

    TimelineSegment.prototype.handles = [null, null];

    function TimelineSegment(layer, config) {
      var me, w;
      this.layer = layer;
      me = this;
      w = 50;
      this.opts = jQuery.extend(this.opts, config);
      this.group = new Kinetic.Group({
        name: 'rect-group',
        x: this.opts.x,
        y: 0,
        width: w,
        height: this.opts.height,
        draggable: true,
        dragBoundFunc: function(pos) {
          return {
            x: pos.x >= 0 ? pos.x : 0,
            y: this.getAbsolutePosition().y
          };
        }
      });
      this.delete_button = new Kinetic.Text({
        text: 'X',
        x: w,
        y: 0,
        fill: 'black'
      });
      this.shape = new Kinetic.Rect({
        x: 0,
        y: 0,
        width: w,
        height: this.opts.height,
        fill: 'green',
        stroke: 'black',
        strokeWidth: 2,
        opacity: this.opts.rectOpacity
      });
      this.group.on('mouseover', function() {
        this.setOpacity(me.opts.rectHoverOpacity);
        document.body.style.cursor = 'pointer';
        return me.layer.draw();
      });
      this.group.on('mouseout', function() {
        this.setOpacity(me.opts.rectOpacity);
        document.body.style.cursor = 'default';
        return me.layer.draw();
      });
      this.delete_button.on('click', function() {
        me.group.destroy();
        return me.layer.draw();
      });
      this.handles[0] = new Kinetic.Rect({
        x: -2,
        y: (this.opts.height / 2) - 2,
        width: 4,
        height: 4,
        fill: 'blue'
      });
      this.handles[1] = new Kinetic.Rect({
        x: w - 2,
        y: (this.opts.height / 2) - 2,
        width: 4,
        height: 4,
        fill: 'blue'
      });
      this.group.add(this.shape);
      this.group.add(this.delete_button);
      this.group.add(this.handles[0]);
      this.group.add(this.handles[1]);
      this.layer.add(this.group);
      this.layer.draw();
    }

    return TimelineSegment;

  })();

}).call(this);
